Update Installer

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -4,6 +4,17 @@ sudo apt upgrade -y
 sudo apt install unzip -y
 sudo apt install python3.9 -y
 sudo apt install python3-pip -y
+
+if [[ -f /etc/os-release ]]; then
+    source /etc/os-release
+    release=$ID
+elif [[ -f /usr/lib/os-release ]]; then
+    source /usr/lib/os-release
+    release=$ID
+else
+    echo "Failed to check the system OS, please contact the author!" >&2
+    exit 1
+fi
 enable_bbr() {
     if grep -q "net.core.default_qdisc=fq" /etc/sysctl.conf && grep -q "net.ipv4.tcp_congestion_control=bbr" /etc/sysctl.conf; then
         echo -e "${green}BBR is already enabled!${plain}"
